services:
  postgres:
    image: postgres:16
    container_name: finance-postgres
    environment:
      POSTGRES_DB: FinancialWebProgram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 357159
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-keycloak-db.sql:/docker-entrypoint-initdb.d/init-keycloak-db.sql
    networks:
      - finance-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  #KEYCLOAK
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: finance-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://finance-postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 357159
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8180
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
    ports:
      - "8180:8080"
    command:
      - start-dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - finance-network
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
  openldap:
    image: osixia/openldap:1.5.0
    container_name: finance-openldap
    environment:
      LDAP_ORGANISATION: "Finance Portal"
      LDAP_DOMAIN: "financeportal.com"
      LDAP_ADMIN_PASSWORD: "admin123"
      LDAP_CONFIG_PASSWORD: "config123"
      LDAP_RFC2307BIS_SCHEMA: "true"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_TLS_VERIFY_CLIENT: "never"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d
    networks:
      - finance-network

  mailhog:
    image: mailhog/mailhog
    container_name: finance-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - finance-network

  phpldapadmin:
      image: osixia/phpldapadmin:0.9.0
      container_name: finance-phpldapadmin
      environment:
        PHPLDAPADMIN_LDAP_HOSTS: "finance-openldap"
        PHPLDAPADMIN_HTTPS: "false"
      ports:
        - "8090:80"
      depends_on:
        - openldap
      networks:
        - finance-network


  redis:
    image: redis:7
    container_name: finance-redis
    ports:
      - "6379:6379"
    networks:
      - finance-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: finance-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - finance-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: finance-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://finance-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - finance-network

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.9.0
    container_name: finance-logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      opensearch:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - finance-network

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: finance-opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - finance-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: finance-otel-collector
    command: ["--config=/etc/otelcol/config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol/config.yml
    ports:
      - "4318:4318"
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - finance-network

  backend:
    build:
      context: ./backend/finance-portal-backend
      dockerfile: Dockerfile
    container_name: finance-backend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://finance-postgres:5432/FinancialWebProgram
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 357159
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: finance-kafka:9092

      # KEYCLOAK CONFIG
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/finance-portal
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/finance-portal/protocol/openid-connect/certs

      JAVA_TOOL_OPTIONS: >
        -javaagent:/app/opentelemetry-javaagent.jar
        -Dotel.service.name=finance-backend
        -Dotel.exporter.otlp.endpoint=http://otel-collector:4318
        -Dotel.metrics.exporter=otlp
        -Dotel.logs.exporter=otlp

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
      keycloak:
        condition: service_healthy  #Keycloak'a bağımlı
      otel-collector:
        condition: service_started
    networks:
      - finance-network

  frontend:
    build:
      context: ./frontend/finance-portal-frontend
      dockerfile: Dockerfile
      args:
        VITE_KEYCLOAK_URL: http://localhost:8180
        VITE_API_BASE_URL: http://localhost:8080/api
    container_name: finance-frontend
    ports:
      - "3000:80"
    environment:
          VITE_KEYCLOAK_URL: http://localhost:8180
          VITE_API_BASE_URL: http://localhost:8080/api
    depends_on:
      backend:
        condition: service_started
    networks:
      - finance-network

volumes:
  postgres_data:
  opensearch_data:
  openldap_data:
  openldap_config:

networks:
  finance-network:
    driver: bridge