input {
  kafka {
    bootstrap_servers => "finance-kafka:9092"
    topics => ["application-logs"]
    codec => json
  }
}

filter {
  json {
    source => "message"
    skip_on_invalid_json => true
  }
}

output {
  opensearch {
    hosts => ["http://finance-opensearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}